#ifndef MANTISMANAGERTESTQT_GLOBAL_H
#define MANTISMANAGERTESTQT_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef MANTISMANAGERTESTQT_LIB
# define MANTISMANAGERTESTQT_EXPORT Q_DECL_EXPORT
#else
# define MANTISMANAGERTESTQT_EXPORT Q_DECL_IMPORT
#endif

#endif // MANTISMANAGERTESTQT_GLOBAL_H
