#ifndef MANTISVIEWERCONSOLEQTTEST_GLOBAL_H
#define MANTISVIEWERCONSOLEQTTEST_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef MANTISVIEWERCONSOLEQTTEST_LIB
# define MANTISVIEWERCONSOLEQTTEST_EXPORT Q_DECL_EXPORT
#else
# define MANTISVIEWERCONSOLEQTTEST_EXPORT Q_DECL_IMPORT
#endif

#endif // MANTISVIEWERCONSOLEQTTEST_GLOBAL_H
